version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    container_name: "postgres-boilerplate"
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432